{"uid":"7637f1114feafca3","name":"Проверка можно изменить никнейм","fullName":"tests.test_editing_profile.TestEditingProfile#test_you_can_change_your_nickname","historyId":"5af1413db6c48e030524cc9a70ef831f","time":{"start":1739310058686,"stop":1739310058686,"duration":0},"description":"Проверяется на пользователе Aleska","descriptionHtml":"<p>Проверяется на пользователе Aleska</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message:","statusTrace":"request = <SubRequest 'login_to_app' for <Function test_you_can_change_your_nickname>>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e6dbd4e4339b5165afaad567693d32d3\")>\n\n    @pytest.fixture(scope='function')\n    @allure.title('Авторизация пользователя в системе')\n    @allure.step('Авторизация пользователя в системе')\n    def login_to_app(request, driver):\n        \"\"\" Фикстура Логина в систему \"\"\"\n        login_page = ApiAuthorization(driver)\n        login_page.user(User.LOGIN, User.PASSWORD)\n        try:\n            later = login_page.find_element(config.locators.RubricPageLocators.locators['Кнопка выберу потом'])\n            login_page.do_click(later)\n        except TimeoutException:\n            element = login_page.find_element(\n                config.locators.MainPageLocators.locators['Листай вниз и найди свои интересы'])\n            login_page.do_click(element)\n        finally:\n>           login_page.do_click(config.locators.MainPageLocators.locators['Листай вниз и найди свои интересы'])\n\nconftest.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase/base_page.py:79: in do_click\n    elem = WebDriverWait(self.driver, wait_time).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"e6dbd4e4339b5165afaad567693d32d3\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f2e1a7e1d00>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n../local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1739309473698,"stop":1739309473699,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1739310058686,"stop":1739310059105,"duration":419},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup","time":{"start":1739310059106,"stop":1739310059107,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Инициализация локаторов","time":{"start":1739310059107,"stop":1739310059107,"duration":0},"status":"passed","steps":[{"name":"Инициализация локаторов","time":{"start":1739310059107,"stop":1739310059107,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"request","value":"<SubRequest 'elements' for <Function test_you_can_change_your_nickname>>"}],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Авторизация пользователя в системе","time":{"start":1739310059107,"stop":1739310083432,"duration":24325},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \n\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 62, in login_to_app\n    login_page.do_click(config.locators.MainPageLocators.locators['Листай вниз и найди свои интересы'])\n  File \"/usr/workspace/base/base_page.py\", line 79, in do_click\n    elem = WebDriverWait(self.driver, wait_time).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Авторизация пользователя в системе","time":{"start":1739310059107,"stop":1739310083432,"duration":24325},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \n\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 62, in login_to_app\n    login_page.do_click(config.locators.MainPageLocators.locators['Листай вниз и найди свои интересы'])\n  File \"/usr/workspace/base/base_page.py\", line 79, in do_click\n    elem = WebDriverWait(self.driver, wait_time).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[{"name":"request","value":"<SubRequest 'login_to_app' for <Function test_you_can_change_your_nickname>>"},{"name":"driver","value":"<selenium.webdriver.chrome.webdriver.WebDriver (session=\"e6dbd4e4339b5165afaad567693d32d3\")>"}],"shouldDisplayMessage":true,"attachmentsCount":0,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1739310083442,"stop":1739310083634,"duration":192},"status":"passed","steps":[],"attachments":[{"uid":"49fa389f1caa5694","name":"page_source","source":"49fa389f1caa5694.html","type":"text/html","size":27593},{"uid":"e06243221fdbd86c","name":"screenshot","source":"e06243221fdbd86c.png","type":"image/png","size":55150},{"uid":"f96e0b46d75fbf2e","name":"browser_logs","source":"f96e0b46d75fbf2e.txt","type":"text/plain","size":7068}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":3,"stepsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"feature","value":"Редактирование профиля"},{"name":"severity","value":"Critical"},{"name":"tag","value":"regression"},{"name":"tag","value":"editing_profile"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_editing_profile"},{"name":"subSuite","value":"TestEditingProfile"},{"name":"host","value":"e56e35b24cd4"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_editing_profile"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":5,"skipped":0,"passed":39,"unknown":0,"total":44},"items":[{"uid":"68b31e85950c1a4e","status":"passed","time":{"start":1738951591684,"stop":1738951598916,"duration":7232}},{"uid":"da982a6d65523fd7","status":"broken","statusDetails":"selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document\n  (Session info: headless chrome=112.0.5615.165); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception","time":{"start":1738874898650,"stop":1738874903111,"duration":4461}},{"uid":"e30f423761b5c38","status":"passed","time":{"start":1738871581734,"stop":1738871588466,"duration":6732}},{"uid":"4fd83261a0e7021b","status":"broken","statusDetails":"selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document\n  (Session info: headless chrome=112.0.5615.165); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception","time":{"start":1738864917848,"stop":1738864923290,"duration":5442}},{"uid":"a84ed7b0e1042b75","status":"passed","time":{"start":1738268572661,"stop":1738268580414,"duration":7753}},{"uid":"5478376fa555deff","status":"passed","time":{"start":1738099011962,"stop":1738099018174,"duration":6212}},{"uid":"5ae760cbdac93f73","status":"passed","time":{"start":1738005023476,"stop":1738005029681,"duration":6205}},{"uid":"636de1212c0d62c2","status":"passed","time":{"start":1738002352581,"stop":1738002358929,"duration":6348}},{"uid":"b0abf6131cefe281","status":"passed","time":{"start":1737928091012,"stop":1737928129865,"duration":38853}},{"uid":"c59d8d030324cc9a","status":"passed","time":{"start":1737842630875,"stop":1737842638642,"duration":7767}},{"uid":"d1788e592dab9476","status":"passed","time":{"start":1737831917763,"stop":1737831925507,"duration":7744}},{"uid":"376e1634ae1ac097","status":"passed","time":{"start":1737799253694,"stop":1737799261461,"duration":7767}},{"uid":"49a73a6deb2537c3","status":"passed","time":{"start":1737757527080,"stop":1737757534810,"duration":7730}},{"uid":"7efaa490a52e6d8b","status":"passed","time":{"start":1737744485092,"stop":1737744492840,"duration":7748}},{"uid":"c608713815489703","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: Не найден элемент с локатором ('xpath', '//div[contains(@class,\"user-info_about\")]')","time":{"start":1737652269373,"stop":1737652304858,"duration":35485}},{"uid":"e834712cfb76cb8a","status":"passed","time":{"start":1737569893206,"stop":1737569902142,"duration":8936}},{"uid":"e0f8bd4f51b39278","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","time":{"start":1737568961214,"stop":1737568961214,"duration":0}},{"uid":"e5d9e76d640049ab","status":"passed","time":{"start":1734034326107,"stop":1734034332506,"duration":6399}},{"uid":"bdedcac584185442","status":"passed","time":{"start":1733937002206,"stop":1733937009936,"duration":7730}},{"uid":"84ae6ba65fe040b5","status":"passed","time":{"start":1733865461949,"stop":1733865468130,"duration":6181}}]},"tags":["editing_profile","regression"]},"source":"7637f1114feafca3.json","parameterValues":[]}